<a href="https://colab.research.google.com/github/prajwalghule999/Task23/blob/main/Task23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1 Linear Regration (California Housing Price Dataset)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import joblib
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import files
uploded = files.upload()

In [ ]:
df = "/content/housing.csv"
df = pd.read_csv(df)
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY

In [ ]:
df.shape

(20640, 10)

In [ ]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
df.dropna(subset=["total_bedrooms"], inplace=True)

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
X = df.drop("median_house_value", axis=1)

y = df["median_house_value"]

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
columns = X.columns.tolist()

joblib.dump(columns, "columns.pkl")

['columns.pkl']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
joblib.dump(model, "LR_housing.pkl")

['LR_housing.pkl']

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

R2 Score: 0.6488402154431994

In [ ]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(result.head(10))

     Actual      Predicted
0  245800.0  201882.959868
1  137900.0  147279.682144
2  218200.0  207796.609798
3  220800.0  180487.576722
4  170500.0  190323.923130
5   75000.0   95437.897104
6  269400.0  287156.451612
7  228900.0  257624.771805
8  500001.0  385383.556151
9   80800.0   62548.197551

Question 2

In [ ]:
from google.colab import files
uploded = files.upload()

Saving Bank Customer.csv to Bank Customer.csv

In [ ]:
df = "/content/Bank Customer.csv"
df = pd.read_csv(df)
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)